Initial setup
kboiiz/air-quality pull request #3
Opened 2022-11-22 14:26 UTC by myshkins

*revised docker-compose.yml
    * fixed volume mapping so that development servers can pickup changes and reload
    * added timezone environment variables
* added .gitignore
* removed unused directories

2022-11-22 16:10 UTC, hucksy commented on code/docker-compose.dev.yml
>        - POSTGRES_PASSWORD=password
Maybe these should come from the .env file?

2022-11-22 16:14 UTC, hucksy requested changes
I dig it! I had a couple thoughts that maybe we can discuss on our call:
* Can we use a single .env file? seems a little hectic having them in multiple places
* Maybe we could add profiles to the docker compose file? these let you run only certain services for debugging/development: https://docs.docker.com/compose/profiles/
* Also do we need the top level  "code" directory?

2022-11-23 23:50 UTC, myshkins commented
aight made those changes. I added the profiles, which is pretty slick thanks for pointing that out.

2022-11-29 21:31 UTC, hucksy approved these changes
righteous

2022-11-29 21:31 UTC, closed without merging