Feature/etl tester
kboiiz/air-quality pull request #8
Opened 2023-01-03 21:56 UTC by myshkins

pr to merge the airnow etl branch to develop

2023-01-03 22:28 UTC, hucksy commented on .env.dev
we should add this to the git ignore file

2023-01-03 22:29 UTC, hucksy commented on _df_test.py
> +
prob don't want this test file included

2023-01-03 22:32 UTC, hucksy commented on _test.py
> +extract_current_data()
should this test file also be removed?

2023-01-03 22:33 UTC, hucksy commented on merged-data.csv
> +station_name,datetime,pm_10_conc,pm_10_AQI,pm_10_cat,pm_25_conc,pm_25_AQI,pm_25_AQI_cat
maybe we should have a cleanup process to delete the csv files after they're loaded?

2023-01-03 22:34 UTC, hucksy commented on services/air_app/app/home/static/home.js
> +})
i don't know js...but look sick!

2023-01-03 22:37 UTC, hucksy commented on services/air_app/app/static/src/js/main.js
> +console.log('hellow')
we can remove the console.log

2023-01-03 22:45 UTC, hucksy commented on services/api/app/api/__init__.py
> -    return app
I like the app factory structure here...keep this maybe? Tiangolo has some great docs about using routers (which are kinda like flask blueprints): https://fastapi.tiangolo.com/tutorial/bigger-applications/

2023-01-03 22:49 UTC, hucksy commented on services/api/main.py
> +    "postgresql+psycopg2://airflow:airflow@postgres/airnow",
I think the db uri should come from a .env variable

2023-01-03 22:58 UTC, hucksy commented on services/api/main.py
> +
^ this is neat!

2023-01-03 23:01 UTC, hucksy commented on services/api/main.py
> +        response = result.all()
do we want just 1 result here? or 5?

2023-01-03 23:03 UTC, hucksy commented on services/api/main.py
> +def query_airnow(period, station):
what is the period input here? doesn't look like it's used

2023-01-03 23:09 UTC, hucksy commented on services/dags/airnow_etl.py
> +
in vscode you can right click in the editor, and there's an option for "sort imports"...which is nice to keep imports alphabetized and easier to read

2023-01-03 23:10 UTC, hucksy commented on services/dags/airnow_etl.py
> +    "API_KEY": "AA5AB45D-9E64-41DE-A918-14578B9AC816",
api key can use a .env variable

2023-01-03 23:22 UTC, hucksy commented on services/dags/sql/airnow_load_prod_stations.sql
> +    ON CONFLICT DO NOTHING
should we update on conflict?

2023-01-03 23:22 UTC, hucksy commented on services/dags/sql/airnow_load_to_prod_data.sql
> +ON CONFLICT DO NOTHING
also here...update on conflict?

2023-01-03 23:25 UTC, hucksy commented on services/api/main.py
> +    return result
similar to the comment above on routers, maybe we could organize this a bit better with a router. We'll be adding more endpoints that will use different routers.

2023-01-03 23:26 UTC, hucksy commented on services/api/main.py
> +
we can also type hint the return values for all the functions here

2023-01-03 23:27 UTC, hucksy requested changes
That's a lot of code, good stuff dude. Lemme know if you want to chat about any of my comments here, some of them are definitely debatable.

2023-01-04 18:53 UTC, myshkins commented on services/dags/sql/airnow_load_prod_stations.sql
> +    ON CONFLICT DO NOTHING
select (specify column names)

2023-01-10 18:48 UTC, closed without merging